# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

controller:
  image:
    repository: quay.io/metallb/controller
    # renovate: datasource=docker depName=quay.io/metallb/controller
    tag: "v0.15.2"
speaker:
  image:
    repository: quay.io/metallb/speaker
    # renovate: datasource=docker depName=quay.io/metallb/speaker
    tag: "v0.15.2"
  frr:
    image:
      repository: quay.io/frrouting/frr
      # renovate: datasource=docker depName=quay.io/frrouting/frr
      tag: "9.1.3"