# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dev
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - "###ZARF_VAR_BASE_IP###.200-###ZARF_VAR_BASE_IP###.215"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
