# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

name: Test UDS RKE2 Demo

# todo: currently broken, need big boy runners

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "CODEOWNERS"
  workflow_dispatch:
  workflow_call:

jobs:
  test-clean-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install UDS CLI
        uses: defenseunicorns/setup-uds@ab842abcad1f7a3305c2538e3dd1950d0daacfa5 # v1.0.1
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: v0.27.11

      - name: "Set up Lima"
        uses: lima-vm/lima-actions/setup@v1
        id: lima-actions-setup

      - name: Create and deploy the uds-rke2-demo bundle
        run: uds run --no-progress

      - name: Validate uds-rke2-demo bundle
        run: uds run validate --no-progress

      - name: Debug Output
        if: ${{ always() }}
        uses: ./.github/actions/debug-output
